//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class arac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public arac()
        {
            this.servis = new HashSet<servi>();
        }
    
        public int aracID { get; set; }
        public string plaka { get; set; }
        public int markaID { get; set; }
        public int modelID { get; set; }
        public int musteriID { get; set; }
        public Nullable<int> modelYil { get; set; }
        public string ruhsatNo { get; set; }
        public string saseNo { get; set; }
        public string motorNo { get; set; }
    
        public virtual aracmodel aracmodel { get; set; }
        public virtual musteri musteri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servi> servis { get; set; }
    }
}
