//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class otoservisdbEntities : DbContext
    {
        public otoservisdbEntities()
            : base("name=otoservisdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<arac> aracs { get; set; }
        public virtual DbSet<aracmarka> aracmarkas { get; set; }
        public virtual DbSet<aracmodel> aracmodels { get; set; }
        public virtual DbSet<bolumler> bolumlers { get; set; }
        public virtual DbSet<kullanici> kullanicis { get; set; }
        public virtual DbSet<musteri> musteris { get; set; }
        public virtual DbSet<parca> parcas { get; set; }
        public virtual DbSet<pozisyonlar> pozisyonlars { get; set; }
        public virtual DbSet<servi> servis { get; set; }
        public virtual DbSet<serviskalem> serviskalems { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
