//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici
    {
        public int kullaniciID { get; set; }
        public string kullaniciAdi { get; set; }
        public string parola { get; set; }
        public string tckn { get; set; }
        public string adSoyad { get; set; }
        public System.DateTime iseGirisTarihi { get; set; }
        public int bolumID { get; set; }
        public int pozisyonID { get; set; }
    
        public virtual bolumler bolumler { get; set; }
        public virtual pozisyonlar pozisyonlar { get; set; }
    }
}
