//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class servi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servi()
        {
            this.serviskalems = new HashSet<serviskalem>();
        }
    
        public int servisID { get; set; }
        public int aracID { get; set; }
        public string aciklama { get; set; }
        public System.DateTime servisGiris { get; set; }
        public Nullable<System.DateTime> servisCikis { get; set; }
    
        public virtual arac arac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<serviskalem> serviskalems { get; set; }
    }
}
