//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class serviskalem
    {
        public int serviskalemID { get; set; }
        public int servisID { get; set; }
        public int parcaID { get; set; }
        public Nullable<int> adet { get; set; }
        public string aciklama { get; set; }
    
        public virtual parca parca { get; set; }
        public virtual servi servi { get; set; }
    }
}
